version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: rto-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: restaurantdb
    volumes:
      - mongo_data:/data/db
      - ./db/seed:/docker-entrypoint-initdb.d:ro
    networks:
      - rto-net

  backend:
    build: ./backend
    container_name: rto-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      NODE_ENV: production
      MONGO_URI: mongodb://rto-mongo:27017/restaurantdb
      JWT_SECRET: devsecret
      CORS_ORIGIN: "*"
    depends_on:
      - mongo
    networks:
      - rto-net

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: http://172.19.71.29:5000/api
    container_name: rto-frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      VITE_API_BASE_URL: http://172.19.71.29:5000/api
    depends_on:
      - backend
    networks:
      - rto-net

volumes:
  mongo_data:

networks:
  rto-net:
    driver: bridge
